package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

func initConfig(args []string, out, errOut io.Writer) int {
	fs := flag.NewFlagSet("init", flag.ContinueOnError)
	fs.SetOutput(errOut)
	profile := fs.String("profile", "balanced", "security profile: balanced, strict, or developer")
	outputPath := fs.String("output", "latch.yaml", "destination policy path, or - for stdout")
	agent := fs.String("agent", envOrDefault("LATCH_AGENT", "desktop-agent"), "initial trusted agent ID")
	force := fs.Bool("force", false, "replace an existing destination")
	if err := fs.Parse(args); err != nil {
		return 64
	}
	if fs.NArg() != 0 {
		fmt.Fprintln(errOut, "init does not accept positional arguments")
		return 64
	}
	content, err := renderProfile(*profile, strings.TrimSpace(*agent))
	if err != nil {
		fmt.Fprintln(errOut, err)
		return 64
	}
	if *outputPath == "-" {
		fmt.Fprint(out, content)
		return 0
	}
	absolutePath, err := filepath.Abs(*outputPath)
	if err != nil {
		fmt.Fprintf(errOut, "resolve output path: %v\n", err)
		return 1
	}
	if err := writePrivateFile(absolutePath, []byte(content), *force); err != nil {
		fmt.Fprintf(errOut, "create policy: %v\n", err)
		return 1
	}
	fmt.Fprintf(out, "Created %s profile at %s\n", strings.ToLower(strings.TrimSpace(*profile)), absolutePath)
	fmt.Fprintf(out, "Next: latch doctor --config %q --agent %q -- <mcp-server-command>\n", absolutePath, strings.TrimSpace(*agent))
	return 0
}

func renderProfile(profile, agentID string) (string, error) {
	profile = strings.ToLower(strings.TrimSpace(profile))
	if profile != "balanced" && profile != "strict" && profile != "developer" {
		return "", fmt.Errorf("--profile must be balanced, strict, or developer")
	}
	if agentID == "" {
		return "", fmt.Errorf("--agent is required")
	}
	quotedAgent, _ := json.Marshal(agentID)

	enforceCapabilities := "false"
	capabilities := ""
	maxActions := 500
	window := "5m"
	switch profile {
	case "strict":
		enforceCapabilities = "true"
		maxActions = 200
		capabilities = `      capabilities:
        - id: workspace-read
          description: Read files inside the launched workspace.
          match:
            tool: filesystem.read
            action: read
            path: "./**"
        - id: safe-http-read
          description: Make read-only HTTP requests.
          match:
            action: network
            http_method: [GET, HEAD]
`
	case "developer":
		maxActions = 2000
		window = "10m"
	}

	return fmt.Sprintf(`# Generated by latch init --profile %s.
version: 1

enforcement:
  approval_threshold: 40
  block_threshold: 90
  allow_unsafe_overrides: false

identity:
  require_verified: true
  enforce_capabilities: %s
  agents:
    - id: %s
%s
budgets:
  store_path: .latch/budgets.json
  lock_timeout: 2s
  rules:
    - id: agent-action-burst
      description: Stop runaway agent loops and cumulative tool abuse.
      match:
        tool: "*"
      max_actions: %d
      window: %s

approvals:
  store_path: .latch/approvals.json
  default_ttl: 15m
  max_ttl: 24h
  lock_timeout: 2s

audit:
  path: .latch/audit.jsonl
  terminal: true

rules:
  - id: block-private-keys
    description: Private keys are never available to AI agents.
    priority: 100
    match:
      path: ["~/.ssh/**", "**/*.pem", "**/*.key"]
    action: block

  - id: block-environment-files
    description: Environment files often contain credentials.
    priority: 100
    match:
      path: ["**/.env", "**/.env.*"]
    action: block

  - id: shell-needs-approval
    description: Shell execution requires a human decision.
    match:
      tool: shell.exec
    action: require_approval

  - id: production-write-needs-approval
    description: Production writes require explicit approval.
    match:
      action: write
      arguments:
        environment: production
    action: require_approval
`, profile, enforceCapabilities, string(quotedAgent), capabilities, maxActions, window), nil
}

func writePrivateFile(path string, data []byte, force bool) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}
	flags := os.O_WRONLY | os.O_CREATE
	if force {
		flags |= os.O_TRUNC
	} else {
		flags |= os.O_EXCL
	}
	file, err := os.OpenFile(path, flags, 0o600)
	if err != nil {
		if os.IsExist(err) {
			return fmt.Errorf("%s already exists; pass --force to replace it", path)
		}
		return err
	}
	if err := file.Chmod(0o600); err != nil {
		_ = file.Close()
		return err
	}
	if _, err := file.Write(data); err != nil {
		_ = file.Close()
		return err
	}
	if err := file.Sync(); err != nil {
		_ = file.Close()
		return err
	}
	return file.Close()
}
