package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/princebabou/Latch/internal/policy"
)

func TestValidatePlaygroundListenRejectsRemoteBinding(t *testing.T) {
	for _, address := range []string{"0.0.0.0:7073", ":7073", "192.0.2.8:7073", "localhost"} {
		if err := validatePlaygroundListen(address); err == nil {
			t.Fatalf("address %q was accepted", address)
		}
	}
	for _, address := range []string{"127.0.0.1:7073", "127.42.0.8:0", "localhost:7073", "[::1]:7073"} {
		if err := validatePlaygroundListen(address); err != nil {
			t.Fatalf("address %q: %v", address, err)
		}
	}
}

func TestLoadPlaygroundPolicyUsesFileOrSafeStarter(t *testing.T) {
	directory := t.TempDir()
	path := filepath.Join(directory, "latch.yaml")
	document := "version: 1\n"
	if err := os.WriteFile(path, []byte(document), 0o600); err != nil {
		t.Fatal(err)
	}
	content, base, sample, err := loadPlaygroundPolicy(path, "desktop-agent", true)
	if err != nil || content != document || sample || base != directory {
		t.Fatalf("content=%q base=%q sample=%t err=%v", content, base, sample, err)
	}

	content, _, sample, err = loadPlaygroundPolicy(filepath.Join(directory, "missing.yaml"), "desktop-agent", false)
	if err != nil || !sample || !strings.Contains(content, "Generated by latch init --profile balanced") {
		t.Fatalf("sample=%t err=%v content=%q", sample, err, content)
	}
	if _, err := policy.Parse([]byte(content), directory); err != nil {
		t.Fatalf("starter policy is invalid: %v", err)
	}
	if _, _, _, err := loadPlaygroundPolicy(filepath.Join(directory, "missing.yaml"), "desktop-agent", true); err == nil {
		t.Fatal("explicitly missing policy was ignored")
	}
}

func TestPlaygroundCommandRejectsRemoteBinding(t *testing.T) {
	var out, errOut strings.Builder
	code := run([]string{"playground", "--listen", "0.0.0.0:7073"}, strings.NewReader(""), &out, &errOut)
	if code != 64 || !strings.Contains(errOut.String(), "local-only") {
		t.Fatalf("code=%d stdout=%q stderr=%q", code, out.String(), errOut.String())
	}
}
